### ISSUE TITLE
How to save annotation texts to Animation.json

### ISSUE THREAD

**Issue by TRYOKETHEPEN** [123Wampir/CADAnimation#12]
Thanks for this project!

After I build my own animation, I saved it, then I got the export file _Animation.json_, but it doesn't contain annotation texts:
![notcontain](https://github.com/user-attachments/assets/6c2026c5-2272-4906-a4f2-cfe3b44a2e57)
When reload _Animation.json_ into the project, all annotation texts become default "Text". 

If I saved the examples, such as the ball valve one, the export file _Animation.json_ does contain texts:
![contain](https://github.com/user-attachments/assets/10df9f2f-90a6-49fc-bd52-97207d088cab)

How to save annotation texts to _Animation.json_?

**Comment by dvronin** [comment]
@TRYOKETHEPEN Thank you for your interest in this project!
To create text animation you need to manually perform keyframe creation. You can make it by click on "Save" button (see image below)
![image](https://github.com/user-attachments/assets/ab94f70e-1dfb-4571-b8e7-88f424daa234)
With only one keyframe you only change initial text value. To perform text animation you need at least two keyframes (make sure that keyframes has different time)
![image](https://github.com/user-attachments/assets/86e86ccb-c5de-4edb-b83c-c6734a44cdb4)
After that its probably gonna work

**Comment by TRYOKETHEPEN** [comment]
> @TRYOKETHEPEN Thank you for your interest in this project! To create text animation you need to manually perform keyframe creation. You can make it by click on "Save" button (see image below) ![image](https://private-user-images.githubusercontent.com/84291114/378008686-ab94f70e-1dfb-4571-b8e7-88f424daa234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzMzMTgsIm5iZiI6MTcyOTQ3MzAxOCwicGF0aCI6Ii84NDI5MTExNC8zNzgwMDg2ODYtYWI5NGY3MGUtMWRmYi00NTcxLWI4ZTctODhmNDI0ZGFhMjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAxMTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYmNhYjBmODY2ZDI4ZTg0NmM4MjM0MTM5Y2E3OTg0YmE5ZmMwMjFjZTg5NTczMDgwYzY1ZTc1NjMxMmMxOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dJxbaSmnwBcNrm_bJkiHJK5CDBKMA2tnODXOJfRLO_o) With only one keyframe you only change initial text value. To perform text animation you need at least two keyframes (make sure that keyframes has different time) ![image](https://private-user-images.githubusercontent.com/84291114/378009321-86e86ccb-c5de-4edb-b83c-c6734a44cdb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzMzMTgsIm5iZiI6MTcyOTQ3MzAxOCwicGF0aCI6Ii84NDI5MTExNC8zNzgwMDkzMjEtODZlODZjY2ItYzVkZS00ZWRiLWI4M2MtYzY3MzRhNDRjZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAxMTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNzJjMzM1OGU0YmQ4ZTM4ZGFmYzFiODhiNmFiZGNlMTA2M2RlYWRhNjE3YjRkMDFlMTlkYTZkZDk0OTYyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-CZceceBoOtcFeJtfH9qOacwEWraL8IfnZk95Z_EDMY) After that its probably gonna work

Thanks a lot!
