### ISSUE TITLE
AmbientLight abnormal, model is all black

### ISSUE THREAD

**Issue by TRYOKETHEPEN** [123Wampir/CADAnimation#13]
_Thank you for this project. I submit different issues for the convenience of other people's reference. I hope I am not annoying._

I get the problem(as the title indicates) by following steps: 
1. _npm run start_ a clean project
2. menu file - import  my model

![importmodel](https://github.com/user-attachments/assets/783e5906-c00b-4413-b96a-ff3ef73a6604)
There is indeed an _ambientLight_ in the scene, but the model is all black.
I tried to increase the _intensity_ of the _ambientLight_ , but only the background became brighter, and the model is still all black.
I understand that the ambient light should illuminate the model evenly. Do I misundertand?

If I add an other light such as _directionalLight_, the color of the model can be displayed:
![directionlight](https://github.com/user-attachments/assets/18ad7ea4-1cb0-482d-9179-52493ecc741e)

If I import a hdr enviroment map such as _src/assets/Env/First.hdr_, the model will be always illuminated even after "show enviroment" button is turned off. And the _ambientLight_'s properties has no difference from initial status.
![hdr](https://github.com/user-attachments/assets/3e061b1a-721a-4559-ac9d-36c039f64177)

**Comment by dvronin** [comment]
Try change material metalness. See this [post](https://discourse.threejs.org/t/ambientlight-doesnt-work-on-my-imported-model/47524) and example below
![image](https://github.com/user-attachments/assets/70dd831f-8176-43c1-a5d8-0ea53043f352)
Hope it helps you.
> If I import a hdr enviroment map such as src/assets/Env/First.hdr, the model will be always illuminated even after "show enviroment" button is turned off

I just did it one direction. There is no way to disable hdr image after you load it.

**Comment by TRYOKETHEPEN** [comment]
Thank you for your detailed reply, it helps a lot! Also inspire me that next time I should  search 'threejs + xxx' if similar problem occurs.
